import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans_KR, Lemon } from 'next/font/google';

export const metadata: Metadata = {
    title: 'P',
    description: 'Generated by create next app',
};

export const notoSansKr = Noto_Sans_KR({
    weight: ['500'],
    subsets: ['latin'],
});

export const lemon = Lemon({
    weight: ['400'],
    subsets: ['latin'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={lemon.className}>{children}</body>
        </html>
    );
}
