import type { Metadata } from 'next';
import './globals.css';
import { Lemon } from 'next/font/google';

export const metadata: Metadata = {
    title: 'P',
    description: 'Generated by create next app',
};

const lemon = Lemon({
    weight: ['400'],
    subsets: ['latin'],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={lemon.className}>{children}</body>
        </html>
    );
}
